CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE identity.users (
    "Id" uuid PRIMARY KEY,
    "PublicId" uuid NOT NULL UNIQUE,
    "DisplayName" varchar(120) NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedAt" timestamptz NULL,
    "LastLoginAt" timestamptz NULL,
    "IsOnboardingCompleted" boolean NOT NULL DEFAULT false,
    "UserName" varchar(256), "NormalizedUserName" varchar(256),
    "Email" varchar(256), "NormalizedEmail" varchar(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text, "SecurityStamp" text, "ConcurrencyStamp" text,
    "PhoneNumber" text, "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamptz, "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);
CREATE UNIQUE INDEX ix_users_normalized_user_name ON identity.users ("NormalizedUserName") WHERE "NormalizedUserName" IS NOT NULL;
CREATE INDEX ix_users_normalized_email ON identity.users ("NormalizedEmail");

CREATE TABLE app."AspNetRoles" (
    "Id" uuid PRIMARY KEY, "Name" varchar(256), "NormalizedName" varchar(256), "ConcurrencyStamp" text
);
CREATE UNIQUE INDEX ix_roles_normalized_name ON app."AspNetRoles" ("NormalizedName") WHERE "NormalizedName" IS NOT NULL;
CREATE TABLE app."AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" uuid NOT NULL REFERENCES app."AspNetRoles"("Id") ON DELETE CASCADE,
    "ClaimType" text, "ClaimValue" text
);
CREATE TABLE app."AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "ClaimType" text, "ClaimValue" text
);
CREATE TABLE app."AspNetUserLogins" (
    "LoginProvider" text NOT NULL, "ProviderKey" text NOT NULL, "ProviderDisplayName" text,
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey")
);
CREATE TABLE app."AspNetUserRoles" (
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "RoleId" uuid NOT NULL REFERENCES app."AspNetRoles"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);
CREATE TABLE app."AspNetUserTokens" (
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "LoginProvider" text NOT NULL, "Name" text NOT NULL, "Value" text,
    PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE TABLE identity.refresh_tokens (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PublicId" uuid NOT NULL UNIQUE, "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "TokenHash" varchar(128) NOT NULL UNIQUE, "ExpiresAt" timestamptz NOT NULL,
    "RevokedAt" timestamptz, "ReplacedByTokenHash" varchar(128)
);

CREATE TABLE app.topics (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "Slug" varchar(120) NOT NULL UNIQUE, "NameVi" varchar(160) NOT NULL,
    "DescriptionVi" varchar(1000), "SortOrder" integer NOT NULL, "Status" integer NOT NULL
);
CREATE TABLE app.vocabularies (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "TopicId" bigint NOT NULL REFERENCES app.topics("Id") ON DELETE RESTRICT,
    "Simplified" varchar(80) NOT NULL, "Traditional" varchar(80), "Pinyin" varchar(160) NOT NULL,
    "MeaningVi" varchar(500) NOT NULL, "PartOfSpeech" varchar(80), "AudioUrl" varchar(1000),
    "HskLevel" integer NOT NULL, "Status" integer NOT NULL,
    UNIQUE ("Simplified", "Pinyin", "HskLevel")
);
CREATE TABLE app.vocabulary_examples (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "VocabularyId" bigint NOT NULL REFERENCES app.vocabularies("Id") ON DELETE CASCADE,
    "ChineseText" varchar(500) NOT NULL, "Pinyin" varchar(700) NOT NULL,
    "MeaningVi" varchar(1000) NOT NULL, "AudioUrl" varchar(1000), "SortOrder" integer NOT NULL
);
CREATE TABLE app.lessons (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "TopicId" bigint NOT NULL REFERENCES app.topics("Id") ON DELETE RESTRICT,
    "Slug" varchar(160) NOT NULL UNIQUE, "TitleVi" varchar(250) NOT NULL,
    "DescriptionVi" varchar(1500), "EstimatedMinutes" integer NOT NULL,
    "SortOrder" integer NOT NULL, "Status" integer NOT NULL
);
CREATE TABLE app.lesson_vocabularies (
    "LessonId" bigint NOT NULL REFERENCES app.lessons("Id") ON DELETE CASCADE,
    "VocabularyId" bigint NOT NULL REFERENCES app.vocabularies("Id") ON DELETE RESTRICT,
    "SortOrder" integer NOT NULL, PRIMARY KEY ("LessonId", "VocabularyId")
);
CREATE TABLE app.user_profiles (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid NOT NULL UNIQUE REFERENCES identity.users("Id") ON DELETE CASCADE,
    "CurrentLevel" integer NOT NULL, "Goal" varchar(300) NOT NULL,
    "DailyGoalMinutes" integer NOT NULL, "TimeZone" varchar(80) NOT NULL
);
CREATE TABLE app.user_vocabulary_progress (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "VocabularyId" bigint NOT NULL REFERENCES app.vocabularies("Id") ON DELETE CASCADE,
    "Mastery" integer NOT NULL, "CorrectCount" integer NOT NULL, "IncorrectCount" integer NOT NULL,
    "LastReviewedAt" timestamptz, UNIQUE ("UserId", "VocabularyId")
);
CREATE TABLE app.user_lesson_progress (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "LessonId" bigint NOT NULL REFERENCES app.lessons("Id") ON DELETE CASCADE,
    "CompletionPercent" integer NOT NULL, "StartedAt" timestamptz, "CompletedAt" timestamptz,
    UNIQUE ("UserId", "LessonId")
);
CREATE TABLE app.favorite_vocabularies (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "VocabularyId" bigint NOT NULL REFERENCES app.vocabularies("Id") ON DELETE CASCADE,
    UNIQUE ("UserId", "VocabularyId")
);
CREATE TABLE app.review_schedules (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "VocabularyId" bigint NOT NULL REFERENCES app.vocabularies("Id") ON DELETE CASCADE,
    "DueAt" timestamptz NOT NULL, "IntervalDays" integer NOT NULL,
    "EaseFactor" numeric(4,2) NOT NULL, "RepetitionCount" integer NOT NULL, "LastRating" integer,
    UNIQUE ("UserId", "VocabularyId")
);

CREATE TABLE app.quizzes (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "LessonId" bigint REFERENCES app.lessons("Id") ON DELETE SET NULL,
    "TitleVi" varchar(250) NOT NULL, "PassingScore" integer NOT NULL, "Status" integer NOT NULL
);
CREATE TABLE app.quiz_questions (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "QuizId" bigint NOT NULL REFERENCES app.quizzes("Id") ON DELETE CASCADE,
    "Type" integer NOT NULL, "PromptVi" varchar(1500) NOT NULL,
    "ExplanationVi" varchar(3000), "SortOrder" integer NOT NULL
);
CREATE TABLE app.quiz_options (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "QuestionId" bigint NOT NULL REFERENCES app.quiz_questions("Id") ON DELETE CASCADE,
    "Text" varchar(1000) NOT NULL, "IsCorrect" boolean NOT NULL, "SortOrder" integer NOT NULL
);
CREATE TABLE app.quiz_attempts (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid NOT NULL REFERENCES identity.users("Id") ON DELETE CASCADE,
    "QuizId" bigint NOT NULL REFERENCES app.quizzes("Id") ON DELETE RESTRICT,
    "Score" integer NOT NULL, "StartedAt" timestamptz NOT NULL, "CompletedAt" timestamptz
);
CREATE TABLE app.quiz_answers (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "AttemptId" bigint NOT NULL REFERENCES app.quiz_attempts("Id") ON DELETE CASCADE,
    "QuestionId" bigint NOT NULL REFERENCES app.quiz_questions("Id") ON DELETE RESTRICT,
    "SelectedOptionId" bigint REFERENCES app.quiz_options("Id") ON DELETE SET NULL,
    "TextAnswer" varchar(2000), "IsCorrect" boolean NOT NULL
);

CREATE TABLE app.content_reports (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "ReporterUserId" uuid NOT NULL, "EntityType" varchar(100) NOT NULL, "EntityPublicId" uuid NOT NULL,
    "Reason" varchar(250) NOT NULL, "Description" varchar(3000), "Status" integer NOT NULL,
    "ResolvedByUserId" uuid, "ResolvedAt" timestamptz
);
CREATE TABLE app.product_events (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid, "Name" varchar(160) NOT NULL, "PropertiesJson" jsonb,
    "SessionId" varchar(160), "ClientPlatform" varchar(80)
);
CREATE TABLE app.ai_usage_logs (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "UserId" uuid, "Feature" varchar(120) NOT NULL, "Model" varchar(120) NOT NULL,
    "InputTokens" integer NOT NULL, "OutputTokens" integer NOT NULL, "DurationMs" integer NOT NULL,
    "Succeeded" boolean NOT NULL, "ErrorCode" varchar(120)
);
CREATE TABLE app.audit_logs (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "PublicId" uuid NOT NULL UNIQUE,
    "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz,
    "ActorUserId" uuid, "Action" varchar(160) NOT NULL, "EntityType" varchar(120) NOT NULL,
    "EntityId" varchar(160), "BeforeJson" jsonb, "AfterJson" jsonb, "IpAddress" varchar(64)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260803060000_InitialMvpSchema', '8.0.29');

COMMIT;

