<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../ChineseLearning.Application/ChineseLearning.Application.csproj" />
    <ProjectReference Include="../ChineseLearning.Infrastructure/ChineseLearning.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
</Project>
